[project]
name = "aalpy-compro-examples"
version = "1.0.0"
description = "Examples of solving competitive programming problems with automata learning using AALpy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "aalpy-compro",
]
